### ISSUE TITLE
I got an error during calculations.

### ISSUE THREAD

**Issue by AlexanderKozhevin** [Bougakov/Micromake-D1-3D-printer#1]
```
Success! Error: 10 factors requested but only 3, 4, 6 and 7 supported.
```

Have you met smth like this?

**Comment by Bougakov** [comment]
Escher3d calculator supports only up to 7 factors to calibrate: 

- three endstop corrections,
- delta radius,
- two tower angular position corrections, and
- diagonal rod length.

You probably confuse calibration **factors** and calibration test **points**. Calculator can use 10 **points** on the plate to guess 3, 4, 6 or 7 **factors**.
